<?php
session_start();
require_once '../config/config.php';

if (!isset($_SESSION['user_id']) || $_SESSION['role'] !== 'facilitator') {
    http_response_code(403);
    exit("Forbidden");
}

if ($_SERVER['REQUEST_METHOD'] == 'POST' && isset($_POST['markdown_content'])) {
    $course_id = $_POST['course_id'] ?? null;
    $content = $_POST['markdown_content'];

    if ($course_id && !empty($content)) {
        // Same logic as process_markdown.php
        $pattern = '/(?=## Module\s+\d+)/i';
        $sections = preg_split($pattern, $content, -1, PREG_SPLIT_NO_EMPTY);
        
        $conn->beginTransaction();
        try {
            $stmt = $conn->prepare("INSERT INTO modules (course_id, title, content, order_num) VALUES (?, ?, ?, ?)");
            
            $modulesCreated = 0;
            
            foreach ($sections as $section) {
                $section = trim($section);
                if (preg_match('/^## Module\s+(\d+)\s*[:\-]?\s*(.*)$/im', $section, $matches)) {
                    $order_num = intval($matches[1]);
                    $title = trim($matches[2]) ?: "Module $order_num";
                    $module_content = $section;
                    
                    $stmt->execute([$course_id, $title, $module_content, $order_num]);
                    $modulesCreated++;
                }
            }
            
            $conn->commit();
            
            if ($modulesCreated > 0) {
                $_SESSION['msg'] = "$modulesCreated modules successfully generated by AI and created!";
            } else {
                $_SESSION['error'] = "AI generated content, but no valid '## Module X' headers were found.";
            }

        } catch (Exception $e) {
            $conn->rollBack();
            $_SESSION['error'] = 'Failed to process AI markdown: ' . $e->getMessage();
        }
    } else {
        $_SESSION['error'] = 'Error generating content.';
    }
}

header('Location: ' . BASE_URL . '/facilitator');
exit;
